name: owl
description: Tiny app intended to load in a curated set of web pages
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
  shared_preferences:
  google_fonts: ^5.1.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/vecteezy-owl.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true
